GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Holy One", 
    "author": "Stefano Dinino",
    "url" : "http://localhost:3003/blog/2",
    "likes" : 4
}